### ISSUE TITLE
Feature: Add support for IIS

### ISSUE THREAD

**Issue by righettod** [ExcelliumSA/WebConfigurationAuditor#3]
# Describe the feature wanted

Add the support for the analysis of a **IIS** app server using the associated [CIS referential](https://www.cisecurity.org/benchmark/microsoft_iis/).

**TODO list:**
- [x] 1 - Implementation of validation rules based on *[CIS Microsoft IIS 10 Benchmark v1.1.1](https://github.com/ExcelliumSA/WebServerSecureConfigurationReviewAutomationTool/files/5750618/CIS_Microsoft_IIS_10_Benchmark_v1.1.1.pdf)*.
- [x] 2 - Create the associate positive and negative test cases.
- [x] 3 - Update corresponding section in the [HowTo](https://github.com/ExcelliumSA/WebServerSecureConfigurationReviewAutomationTool/blob/master/Howto.md#iis) documentation file.
